---
  - name: Set DEFROUTE=No on routers, servers, clients
    hosts: routers,servers,clients
    become: True
    
    tasks:
      - name: Set DEFROUTE=No
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

      - name: Restart network
        service: 
          name: network
          state: restarted


  - name: inetRouter configuration
    hosts: inetRouter
    become: True

    tasks:
      - name: Set ip forwarding on in /proc and verify token value with the sysctl command
        sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          sysctl_set: yes
          state: present
          reload: yes
      
      - name: IPtables Configuration
        command: echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf

      - name: Restart network
        service: 
          name: network
          state: restarted
    
      - name: IPtables Configuration
        command: iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
      
      - name: ip routing 192.168.0.0/24
        command: ip route add 192.168.0.0/24 via 192.168.255.2

      - name: ip routing 192.168.1.0/24
        command: ip route add 192.168.1.0/24 via 192.168.255.2
      
      - name: ip routing 192.168.2.0/24
        command: ip route add 192.168.2.0/24 via 192.168.255.2

      - name: ip routing 192.168.255.4/30
        command: ip route add 192.168.255.4/30 via 192.168.255.2

      - name: ip routing 192.168.255.8/30
        command: ip route add 192.168.255.8/30 via 192.168.255.2
    
  - name: Routers configuration
    hosts: routers
    become: True

    tasks:
      - name: Set ip forwarding on in /proc and verify token value with the sysctl command
        sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          sysctl_set: yes
          state: present
          reload: yes

  - name: centralRouter Ñonfiguration 
    hosts: centralRouter
    become: True

    tasks:
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
    
      - name: Restart network
        service: 
          name: network
          state: restarted

      - name: ip routing 192.168.2.0/24
        command: ip route add 192.168.2.0/24 via 192.168.255.6
      
      - name: ip routing 192.168.1.0/24
        command: ip route add 192.168.1.0/24 via 192.168.255.10

  - name: Configuration centralServer
    hosts: centralServer
    become: True

    tasks:
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        systemd:
          name: network
          state: reloaded


  - name: Configuration office1Router
    hosts: office1Router
    become: True

    tasks:
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.255.5" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        service: 
          name: network
          state: restarted

  - name: Configuration office1Server
    hosts: office1Server
    become: True

    tasks:
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        service: 
          name: network
          state: restarted

  - name: Configuration testServer1
    hosts: testServer1
    become: True

    tasks:
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.3.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Copy VLAN interface config
        copy:
          src: 'files/network-scripts/ifcfg-vlan2-server'
          dest: '/etc/sysconfig/network-scripts/ifcfg-vlan2'

      - name: Restart network
        service: 
          name: network
          state: restarted

  - name: Configuration testClient1
    hosts: testServer1
    become: True

    tasks:
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.3.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        service: 
          name: network
          state: restarted

  - name: Configuration testServer2
    hosts: testServer2
    become: True

    tasks:
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.3.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        service: 
          name: network
          state: restarted

  - name: Configuration testClient2
    hosts: testServer2
    become: True

    tasks:
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.3.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        service: 
          name: network
          state: restarted

  - name: Configuration office2Router
    hosts: office2Router
    become: True

    tasks:
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.255.9" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        service: 
          name: network
          state: restarted

  - name: Configuration office2Server
    hosts: office2Server
    become: True

    tasks:
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.1.129" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        service: 
          name: network
          state: restarted
...