---
  - name: Install PostgreSQL Repository
    dnf:
      name:  https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: present

  - name: Disable the built-in PostgreSQL module
    command: dnf -qy module disable postgresql

  - name: Install PostgreSQL packages
    package:
      name: "{{ postgresql_packages }}"
      state: present
    notify: PostgreSQL service enable 
...